//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskAsciiArtService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAsciiArtService")]
    public interface IAsciiArtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsciiArtService/ImageToAscii", ReplyAction="http://tempuri.org/IAsciiArtService/ImageToAsciiResponse")]
        string ImageToAscii(byte[] imageByteArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsciiArtService/ImageToAscii", ReplyAction="http://tempuri.org/IAsciiArtService/ImageToAsciiResponse")]
        System.Threading.Tasks.Task<string> ImageToAsciiAsync(byte[] imageByteArray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsciiArtServiceChannel : TaskAsciiArtService.ServiceReference1.IAsciiArtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsciiArtServiceClient : System.ServiceModel.ClientBase<TaskAsciiArtService.ServiceReference1.IAsciiArtService>, TaskAsciiArtService.ServiceReference1.IAsciiArtService {
        
        public AsciiArtServiceClient() {
        }
        
        public AsciiArtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsciiArtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsciiArtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsciiArtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ImageToAscii(byte[] imageByteArray) {
            return base.Channel.ImageToAscii(imageByteArray);
        }
        
        public System.Threading.Tasks.Task<string> ImageToAsciiAsync(byte[] imageByteArray) {
            return base.Channel.ImageToAsciiAsync(imageByteArray);
        }
    }
}
